- name: Check if Wazuh agent bin exists on Ludus for Windows targets
  ansible.builtin.stat:
    path: "{{ ludus_install_directory }}/resources/windows/{{ wazuh_agent_install_package }}"
  register: windows_agent_exists
  delegate_to: localhost

- name: Download the Windows Wazuh agent if it doesn't exist
  ansible.builtin.get_url:
    url: "{{ wazuh_agent_install_package_url }}"
    dest: "{{ ludus_install_directory }}/resources/windows/{{ wazuh_agent_install_package }}"
    mode: "0644"
  delegate_to: localhost
  when: not windows_agent_exists.stat.exists

- name: Create Ludus directory on Windows target if it doesn't exist
  ansible.windows.win_file:
    path: "{{ wazuh_install_directory }}"
    state: directory

- name: Copy Elastic agent to Windows target
  ansible.windows.win_copy:
    src: "{{ ludus_install_directory }}/resources/windows/{{ wazuh_agent_install_package }}"
    dest: "{{ wazuh_install_directory }}"
